import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { store } from './store'
import { Provider } from 'react-redux'
import { Providers } from './providers'
const montserrat = Montserrat({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", '800', "900"] })

export const metadata: Metadata = {
  title: 'TO-DO LIST',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}
